name: bezpieczny_swiat_cyfrowy
description: "Aplikacja edukacyjna, projekt ROPS"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1
  provider: ^6.0.5
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  flutter_tts: ^3.8.0
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo/Bezpieczny Świat Cyfrowy Icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/Logo/Bezpieczny Świat Cyfrowy Icon.png
    - assets/data/scenarios.json
    - assets/audio/
    - assets/images/
